---
version: "3"
services:
 devopsdb:
   image: shaikmustafa/ccitrepo:dbimage
   deploy:
     replicas: 3
   ports:
     - "3306:3306"

 application:
   image: shaikmustafa/ccitrepo:appimage
   deploy:
     replicas: 3
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
