---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: devopsapp
spec:
  replicas: 2
  selector:
    app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
       - name: cont-1
         image: appalashetty/sravani:dbimage
         ports:
          - containerPort: 3306
      imagePullSecrets:
       - name: flm






---
apiversion: v1
kind: Service
metadata:
  name: dbsvc
spec:
  clusterIP: None
  selector:
     app: swiggy
     ports:
     - ports: 3306
       targetPort: 3306
